/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.villejoenrollmentsystem;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aaron
 */
public class StudentsForm extends javax.swing.JFrame {

    /**
     * Creates new form StudentsForm
     */
    public StudentsForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studID = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        studname = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        studcontact = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        studaddress = new javax.swing.JTextPane();
        studemail = new javax.swing.JScrollPane();
        studEmail = new javax.swing.JTextPane();
        gender = new javax.swing.JScrollPane();
        studgender = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        studyrlvl = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        studTable = new javax.swing.JTable();
        save = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Enroll = new javax.swing.JButton();
        Drop = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        EnrolledSubject = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        TeachersForm = new javax.swing.JMenu();
        TForm = new javax.swing.JMenuItem();
        SubjectsForm = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("table");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Student ID");

        name.setText("Name");

        jLabel3.setText("Address");

        jLabel4.setText("Contact");

        jLabel5.setText("Email");

        jLabel6.setText("Gender");

        jLabel7.setText("Student Year Level");

        studID.setEditable(false);
        jScrollPane1.setViewportView(studID);

        jScrollPane2.setViewportView(studname);

        jScrollPane3.setViewportView(studcontact);

        jScrollPane4.setViewportView(studaddress);

        studemail.setViewportView(studEmail);

        gender.setViewportView(studgender);

        jScrollPane7.setViewportView(studyrlvl);

        studTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Contact", "Address", "Email", "Gender", "Student Year Level"
            }
        ));
        studTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studTableMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(studTable);

        save.setText("Save");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });

        delete.setText("Delete");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });

        update.setText("Update");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ENROLLED SUBJECTS");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Enroll.setText("Enroll");
        Enroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnrollMouseClicked(evt);
            }
        });

        Drop.setText("Drop");
        Drop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DropMouseClicked(evt);
            }
        });

        EnrolledSubject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Subject ID", "Subject Code", "Subject Description", "Subject Units", "Schedule"
            }
        ));
        jScrollPane9.setViewportView(EnrolledSubject);

        jLabel10.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("STUDENTS REGISTRATION");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TeachersForm.setText("Forms");

        TForm.setText("Teachers Form");
        TForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFormActionPerformed(evt);
            }
        });
        TeachersForm.add(TForm);

        SubjectsForm.setText("Subjects Form");
        SubjectsForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubjectsFormActionPerformed(evt);
            }
        });
        TeachersForm.add(SubjectsForm);
        TeachersForm.add(jSeparator1);

        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitactionPerformed(evt);
            }
        });
        TeachersForm.add(jMenuItem3);

        jMenuBar1.add(TeachersForm);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7)
                    .addComponent(gender)
                    .addComponent(jScrollPane1)
                    .addComponent(studemail)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                            .addComponent(jScrollPane9))
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Enroll)
                            .addComponent(Drop)
                            .addComponent(save)
                            .addComponent(delete)
                            .addComponent(update)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(563, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(391, 391, 391)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(update)
                        .addGap(281, 281, 281)
                        .addComponent(Enroll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Drop))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(studemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(jLabel10)
                    .addContainerGap(721, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void LoadRecord(){
        VillejoEnrollmentSystem a = new VillejoEnrollmentSystem();
        a.DBConnect();
        
        DefaultTableModel tblmodel = (DefaultTableModel) studTable.getModel();
        tblmodel.setRowCount(0);
        
        try{
            String queryShow = "SELECT * from students;";
            a.rs = a.st.executeQuery(queryShow);
            while(a.rs.next()){
                String studid = a.rs.getString("studID");
                String studname = a.rs.getString("studname");
                String studcontact = a.rs.getString("studcontact");
                String studaddress = a.rs.getString("studaddress");
                String studEmail = a.rs.getString("studEmail");
                String studgender = a.rs.getString("studgender");
                String studyrlvl = a.rs.getString("studyrlvl");
                
            tblmodel.addRow(new Object[]{studid, studname, studcontact, studaddress, studEmail, studgender, studyrlvl});
                
            }
        }catch (Exception ex){
            System.out.println(ex);
        }
    }
    
    public void ShowRecord(){
        DefaultTableModel tblmodel = (DefaultTableModel) studTable.getModel();
        tblmodel.setRowCount(0);
        
        VillejoEnrollmentSystem a = new VillejoEnrollmentSystem();
        a.DBConnect();
        
        try{
            String queryShow = "SELECT * from students;";
            a.rs = a.st.executeQuery(queryShow);
            while (a.rs.next()){
                String studid = a.rs.getString("studID");
                String studname = a.rs.getString("studname");
                String studcontact = a.rs.getString("studcontact");
                String studaddress = a.rs.getString("studaddress");
                String studEmail = a.rs.getString("studEmail");
                String studgender = a.rs.getString("studgender");
                String studyrlvl = a.rs.getString("studyrlvl");
                
                String [] studRecord = {studid, studname, studcontact, studaddress, studEmail, studgender, studyrlvl};
                tblmodel.addRow(studRecord);
            }
        } catch (Exception ex){
            System.out.println(ex);
        }
    }
    public void showEnrolledSubjects(int studentId) {
    Enrolled enrolled = new Enrolled();
    List<Object[]> subjects = enrolled.getEnrolledSubjects(studentId);

    DefaultTableModel model = (DefaultTableModel) EnrolledSubject.getModel(); 
    model.setRowCount(0);

    for (Object[] row : subjects) {
        model.addRow(row);
    }
}

    private void enrollStudent() {
    if (selectedSubjectId == -1) {
        JOptionPane.showMessageDialog(this, "Select a subject in Subject Form first!");
        return;
    }

    int studentId = Integer.parseInt(studID.getText());
    Enrolled enrolled = new Enrolled();

    boolean success = enrolled.enrollStudent(studentId, selectedSubjectId);

    if (success) {
        JOptionPane.showMessageDialog(this, "Student enrolled successfully!");
    } else {
        JOptionPane.showMessageDialog(this, "Student is already enrolled in that subject!");
    }

    showEnrolledSubjects(studentId);
}

// ===== Drop Logic =====
    private void dropStudent() {
    if (selectedSubjectId == -1) {
        JOptionPane.showMessageDialog(this, "Select a subject in Subject Form first!");
        return;
    }

    int studentId = Integer.parseInt(studID.getText());
    Enrolled enrolled = new Enrolled();

    boolean success = enrolled.dropStudent(studentId, selectedSubjectId);

    if (success) {
        JOptionPane.showMessageDialog(this, "Subject dropped successfully!");
    } else {
        JOptionPane.showMessageDialog(this, "Student is not enrolled in that subject.");
    }

    showEnrolledSubjects(studentId);
}

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        Students a = new Students();
        a.SaveRecord(
                studname.getText(),
                studcontact.getText(),
                studaddress.getText(),
                studEmail.getText(),
                studgender.getText(),
                studyrlvl.getText());
        
        ShowRecord();
    }//GEN-LAST:event_saveMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        VillejoEnrollmentSystem a = new VillejoEnrollmentSystem();
        a.DBConnect();
        
        int sID = Integer.parseInt(studID.getText());
        
        Students deleteRec = new Students();
        deleteRec.DeleteRecord(sID);
        
        ShowRecord();
    }//GEN-LAST:event_deleteMouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        int sID = Integer.parseInt(studID.getText());
        String sname = studname.getText();
        String con = studcontact.getText();
        String add = studaddress.getText();
        String mail = studEmail.getText();
        String gen = studgender.getText();
        String yrlvl = studyrlvl.getText();
        
        Students updateRec = new Students();
        updateRec.UpdateRecord(sID, sname, con, add, mail, gen, yrlvl);
        
        ShowRecord();
    }//GEN-LAST:event_updateMouseClicked
     private int selectedSubjectId = -1; 

    public void setSelectedSubject(int subjId) {
    this.selectedSubjectId = subjId;
}
    private void SubjectsFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectsFormActionPerformed
        SubjectForm b = new SubjectForm(this);
        b.setVisible(true);
    }//GEN-LAST:event_SubjectsFormActionPerformed

    private void TFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFormActionPerformed
        TeacherForm a = new TeacherForm();
        a.setVisible(true);
    }//GEN-LAST:event_TFormActionPerformed

    private void ExitactionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitactionPerformed
        dispose();
    }//GEN-LAST:event_ExitactionPerformed

    private void EnrollMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnrollMouseClicked
        enrollStudent();
    }//GEN-LAST:event_EnrollMouseClicked

    private void DropMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DropMouseClicked
        dropStudent();
    }//GEN-LAST:event_DropMouseClicked

    private void studTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studTableMouseClicked
        int selectedRow = studTable.getSelectedRow();
    if (selectedRow >= 0) {
        int studentId = Integer.parseInt(studTable.getValueAt(selectedRow, 0).toString());

        studID.setText(studTable.getValueAt(selectedRow, 0).toString());
        studname.setText(studTable.getValueAt(selectedRow, 1).toString());
        studcontact.setText(studTable.getValueAt(selectedRow, 2).toString());
        studaddress.setText(studTable.getValueAt(selectedRow, 3).toString());
        studEmail.setText(studTable.getValueAt(selectedRow, 4).toString());
        studgender.setText(studTable.getValueAt(selectedRow, 5).toString());
        studyrlvl.setText(studTable.getValueAt(selectedRow, 6).toString());

        showEnrolledSubjects(studentId);
    }//GEN-LAST:event_studTableMouseClicked
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       ShowRecord();
        Students load = new Students();
        load.LoadRecord();
        
        
            studTable.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
            int selectedRow = studTable.getSelectedRow();
            if (selectedRow >= 0) {
            studID.setText(studTable.getValueAt(selectedRow, 0).toString());        
            studname.setText(studTable.getValueAt(selectedRow, 1).toString());      
            studcontact.setText(studTable.getValueAt(selectedRow, 2).toString());   
            studaddress.setText(studTable.getValueAt(selectedRow, 3).toString());   
            studEmail.setText(studTable.getValueAt(selectedRow, 4).toString());     
            studgender.setText(studTable.getValueAt(selectedRow, 5).toString());    
            studyrlvl.setText(studTable.getValueAt(selectedRow, 6).toString());     

        }
    }
});
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Drop;
    private javax.swing.JButton Enroll;
    private javax.swing.JTable EnrolledSubject;
    private javax.swing.JMenuItem SubjectsForm;
    private javax.swing.JMenuItem TForm;
    private javax.swing.JMenu TeachersForm;
    private javax.swing.JButton delete;
    private javax.swing.JScrollPane gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel name;
    private javax.swing.JButton save;
    private javax.swing.JTextPane studEmail;
    private javax.swing.JTextPane studID;
    private javax.swing.JTable studTable;
    private javax.swing.JTextPane studaddress;
    private javax.swing.JTextPane studcontact;
    private javax.swing.JScrollPane studemail;
    private javax.swing.JTextPane studgender;
    private javax.swing.JTextPane studname;
    private javax.swing.JTextPane studyrlvl;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
