/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.villejoenrollmentsystem;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aaron
 */
public class TeacherForm extends javax.swing.JFrame {

    /**
     * Creates new form TeacherForm
     */
    public TeacherForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        studemail = new javax.swing.JScrollPane();
        studEmail = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        gender = new javax.swing.JScrollPane();
        studgender = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        studID = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        studyrlvl = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        studname = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        studTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        studcontact = new javax.swing.JTextPane();
        name = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        studaddress = new javax.swing.JTextPane();
        delete = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        update1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        studemail1 = new javax.swing.JScrollPane();
        temail = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        gender1 = new javax.swing.JScrollPane();
        tdepartment = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        tID = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        tname = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        tTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tcontact = new javax.swing.JTextPane();
        name1 = new javax.swing.JLabel();
        save1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        taddress = new javax.swing.JTextPane();
        delete1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        StudentsForm = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jLabel4.setText("Contact");

        update.setText("Update");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });

        jLabel5.setText("Email");

        studemail.setViewportView(studEmail);

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("STUDENTS REGISTRATION");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel6.setText("Gender");

        jLabel7.setText("Student Year Level");

        gender.setViewportView(studgender);

        jScrollPane1.setViewportView(studID);

        jScrollPane7.setViewportView(studyrlvl);

        jScrollPane2.setViewportView(studname);

        studTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Contact", "Address", "Email", "Gender", "Student Year Level"
            }
        ));
        jScrollPane8.setViewportView(studTable);

        jLabel1.setText("Student ID");

        jScrollPane3.setViewportView(studcontact);

        name.setText("Name");

        save.setText("Save");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });

        jLabel3.setText("Address");

        jScrollPane4.setViewportView(studaddress);

        delete.setText("Delete");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel9.setText("Teacher Contact");

        update1.setText("Update");
        update1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });

        jLabel10.setText("Teacher Email");

        studemail1.setViewportView(temail);

        jLabel11.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("TEACHERS REGISTRATION");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel12.setText("Teacher Department");

        gender1.setViewportView(tdepartment);

        jScrollPane5.setViewportView(tID);

        jScrollPane6.setViewportView(tname);

        tTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Name", "Contact", "Address", "Email", "Department"
            }
        ));
        jScrollPane10.setViewportView(tTable);

        jLabel2.setText("Teacher ID");

        jScrollPane11.setViewportView(tcontact);

        name1.setText("Teacher Name");

        save1.setText("Save");
        save1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });

        jLabel14.setText("Teachers Address");

        jScrollPane12.setViewportView(taddress);

        delete1.setText("Delete");
        delete1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });

        jMenu1.setText("File");

        StudentsForm.setText("StudentsForm");
        StudentsForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentsFormActionPerformed(evt);
            }
        });
        jMenu1.add(StudentsForm);

        jMenuItem2.setText("SubjectsForm");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubjectsForm(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setText("Exit");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                .addComponent(name1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(gender1)
                                .addComponent(jScrollPane5)
                                .addComponent(studemail1)
                                .addComponent(jScrollPane12)
                                .addComponent(jScrollPane11)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(save1)
                            .addComponent(delete1)
                            .addComponent(update1))))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel11)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name1)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(studemail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(gender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addComponent(save1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(delete1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(update1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void ShowRecord() {
        VillejoEnrollmentSystem db = new VillejoEnrollmentSystem();
        db.DBConnect();

        DefaultTableModel model = (DefaultTableModel) tTable.getModel();
        model.setRowCount(0);

        try {
            String query = "SELECT * FROM teachers;";
            db.rs = db.st.executeQuery(query);
            while (db.rs.next()) {
                String id = db.rs.getString("tID");
                String name = db.rs.getString("tname");
                String address = db.rs.getString("taddress");
                String contact = db.rs.getString("tcontact");
                String email = db.rs.getString("temail");
                String department = db.rs.getString("tdepartment");

                model.addRow(new Object[]{id, name, contact, address, email, department});
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        int TID = Integer.parseInt(tID.getText());
        String Tname = tname.getText();
        String Tcon = tcontact.getText();
        String Tadd = taddress.getText();
        String Tmail = temail.getText();
        String Tdep = tdepartment.getText();

        Teachers updateRec = new Teachers();
        updateRec.UpdateRecord(TID, Tname, Tcon, Tadd, Tmail, Tdep);

        ShowRecord();
    }//GEN-LAST:event_updateMouseClicked

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
        Teachers a = new Teachers();
        a.SaveRecord(Integer.parseInt(tID.getText()),
        tname.getText(),
        tcontact.getText(),
        taddress.getText(),
        temail.getText(),
        tdepartment.getText()
    );

ShowRecord();
    }//GEN-LAST:event_saveMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        VillejoEnrollmentSystem a = new VillejoEnrollmentSystem();
        a.DBConnect();

        int TID = Integer.parseInt(tID.getText());

        Teachers deleteRec = new Teachers();
        deleteRec.DeleteRecord(TID);

        ShowRecord();
    }//GEN-LAST:event_deleteMouseClicked

    private void StudentsFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentsFormActionPerformed
        StudentsForm s = new StudentsForm();
        s.setVisible(true);
    }//GEN-LAST:event_StudentsFormActionPerformed

    private void SubjectsForm(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectsForm
        SubjectForm s = new SubjectForm();
        s.setVisible(true);    }//GEN-LAST:event_SubjectsForm

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ShowRecord();
        tTable.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = tTable.getSelectedRow();
                tID.setText(tTable.getValueAt(row, 0).toString());
                tname.setText(tTable.getValueAt(row, 1).toString());
                tcontact.setText(tTable.getValueAt(row, 2).toString());
                taddress.setText(tTable.getValueAt(row, 3).toString());
                temail.setText(tTable.getValueAt(row, 4).toString());
                tdepartment.setText(tTable.getValueAt(row, 5).toString());
            
    }//GEN-LAST:event_formWindowOpened

                });
    
                }
    
         /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentsForm().setVisible(true);
            }
        });
    }       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem StudentsForm;
    private javax.swing.JButton delete;
    private javax.swing.JButton delete1;
    private javax.swing.JScrollPane gender;
    private javax.swing.JScrollPane gender1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JButton save;
    private javax.swing.JButton save1;
    private javax.swing.JTextPane studEmail;
    private javax.swing.JTextPane studID;
    private javax.swing.JTable studTable;
    private javax.swing.JTextPane studaddress;
    private javax.swing.JTextPane studcontact;
    private javax.swing.JScrollPane studemail;
    private javax.swing.JScrollPane studemail1;
    private javax.swing.JTextPane studgender;
    private javax.swing.JTextPane studname;
    private javax.swing.JTextPane studyrlvl;
    private javax.swing.JTextPane tID;
    private javax.swing.JTable tTable;
    private javax.swing.JTextPane taddress;
    private javax.swing.JTextPane tcontact;
    private javax.swing.JTextPane tdepartment;
    private javax.swing.JTextPane temail;
    private javax.swing.JTextPane tname;
    private javax.swing.JButton update;
    private javax.swing.JButton update1;
    // End of variables declaration//GEN-END:variables
}
